name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Build
        run: |
          echo "Testing crumb endpoint..."
          curl -v \
            -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
            -H "ngrok-skip-browser-warning: true" \
            "https://${{ secrets.JENKINS_URL }}/crumbIssuer/api/json"